import fs from "node:fs";
import { expect, test } from "@playwright/test";
import { collectConsoleErrors, criticalRoutes, waitForApp } from "./helpers.js";

function visibleActionSelector() {
  return [
    "button",
    "a[href]",
    "[data-route]",
    "[data-action]",
    "[data-screen]",
    "[data-open]",
  ].join(",");
}

test("V10 clickable inventory covers critical routes", async ({ page }) => {
  const errors = await collectConsoleErrors(page);
  const rows = [];

  for (const route of criticalRoutes) {
    await page.goto(`/#${route}`);
    await waitForApp(page);

    const metrics = await page.evaluate((selector) => {
      const actions = Array.from(document.querySelectorAll(selector)).filter((element) => {
        const rect = element.getBoundingClientRect();
        const style = window.getComputedStyle(element);
        return rect.width > 0 && rect.height > 0 && style.visibility !== "hidden" && style.display !== "none";
      });
      const unlabeled = actions.filter((element) => {
        const label = [
          element.getAttribute("aria-label"),
          element.getAttribute("data-testid"),
          element.textContent,
          element.getAttribute("title"),
        ].join(" ").trim();
        return !label;
      });

      return {
        actionCount: actions.length,
        unlabeledCount: unlabeled.length,
      };
    }, visibleActionSelector());

    expect(metrics.actionCount, `${route} should expose clickable UI`).toBeGreaterThan(2);
    expect(metrics.unlabeledCount, `${route} should avoid unlabeled clickables`).toBeLessThanOrEqual(1);
    rows.push(`| \`${route}\` | ${metrics.actionCount} | ${metrics.unlabeledCount} |`);
  }

  fs.writeFileSync(
    "CLICKABLE_INVENTORY_REPORT.md",
    [
      "# Clickable Inventory Report",
      "",
      "Generated by `tests/e2e/clickable-inventory.spec.js`.",
      "",
      "| Route | Visible clickables | Unlabeled |",
      "| --- | ---: | ---: |",
      ...rows,
      "",
      "Status: V10 critical routes expose clickable UI and keep unlabeled controls within the allowed smoke-test threshold.",
      "",
    ].join("\n"),
  );

  expect(errors).toEqual([]);
});
