import fs from "node:fs";
import { expect, test } from "@playwright/test";
import { collectConsoleErrors, waitForApp } from "./helpers.js";

const reportRoutes = ["/home", "/profile", "/support/live", "/partner-card-preview", "/notifications"];

test("V10 visual QA report records header and overflow status", async ({ page }) => {
  const errors = await collectConsoleErrors(page);
  const rows = [];

  for (const route of reportRoutes) {
    await page.goto(`/#${route}`);
    await waitForApp(page);
    const audit = await page.evaluate(() => {
      const root = document.querySelector("#appRoot");
      const header = document.querySelector('[data-testid="app-header"]');
      const bottom = document.querySelector('[data-testid="app-bottom-bar"]');
      return {
        header: Boolean(header),
        bottom: Boolean(bottom),
        overflow: root ? root.scrollWidth > root.clientWidth + 1 : true,
      };
    });
    expect(audit.header, `${route} header`).toBeTruthy();
    expect(audit.bottom, `${route} bottom bar`).toBeTruthy();
    expect(audit.overflow, `${route} overflow`).toBeFalsy();
    rows.push(`| \`${route}\` | ${audit.header ? "ok" : "missing"} | ${audit.bottom ? "ok" : "missing"} | ${audit.overflow ? "yes" : "no"} |`);
  }

  fs.writeFileSync(
    "VISUAL_QA_REPORT.md",
    [
      "# Visual QA Report",
      "",
      "Generated by `tests/e2e/visual-qa-report.spec.js`.",
      "",
      "| Route | Header | Bottom bar | Horizontal overflow |",
      "| --- | --- | --- | --- |",
      ...rows,
      "",
      "Status: V10 visual smoke checks passed for the sampled core routes.",
      "",
    ].join("\n"),
  );

  expect(errors).toEqual([]);
});
