import fs from "node:fs";
import { expect, test } from "@playwright/test";
import { bottomBarHiddenRoutes, collectConsoleErrors, waitForApp } from "./helpers.js";

const reportRoutes = ["/home", "/profile", "/support/live", "/partner-card-preview", "/notifications"];

test("V10 visual QA report records header and overflow status", async ({ page }) => {
  const errors = await collectConsoleErrors(page);
  const rows = [];

  for (const route of reportRoutes) {
    await page.goto(`/#${route}`);
    await waitForApp(page);
    const audit = await page.evaluate(() => {
      const root = document.querySelector("#appRoot");
      const header = document.querySelector('[data-testid="app-header"]');
      const bottom = document.querySelector('[data-testid="app-bottom-bar"]');
      const stickyProfile = document.querySelector('[data-testid="profile-sticky-preview-button"]');
      const stickyPreview = document.querySelector('[data-testid="partner-preview-sticky-actions"]');
      return {
        header: Boolean(header),
        bottom: Boolean(bottom),
        stickyAction: Boolean(stickyProfile || stickyPreview),
        overflow: root ? root.scrollWidth > root.clientWidth + 1 : true,
      };
    });
    const bottomOrAction = bottomBarHiddenRoutes.has(route) ? audit.stickyAction : audit.bottom;
    expect(audit.header, `${route} header`).toBeTruthy();
    expect(bottomOrAction, `${route} bottom action`).toBeTruthy();
    expect(audit.overflow, `${route} overflow`).toBeFalsy();
    rows.push(`| \`${route}\` | ${audit.header ? "ok" : "missing"} | ${bottomOrAction ? "ok" : "missing"} | ${audit.overflow ? "yes" : "no"} |`);
  }

  fs.writeFileSync(
    "VISUAL_QA_REPORT.md",
    [
      "# Visual QA Report",
      "",
      "Generated by `tests/e2e/visual-qa-report.spec.js`.",
      "",
      "| Route | Header | Bottom action | Horizontal overflow |",
      "| --- | --- | --- | --- |",
      ...rows,
      "",
      "Status: V10 visual smoke checks passed for the sampled core routes.",
      "",
    ].join("\n"),
  );

  expect(errors).toEqual([]);
});
