import {
  AboutPage,
  AccountSettingsPage,
  AppointmentLinkPage,
  BonusPage,
  CalendarPage,
  CapacityPage,
  ContactSettingsPage,
  CreateTicketPage,
  CustomerServicePage,
  CustomersPage,
  HomePage,
  IncomeExpensePage,
  InvoicesPage,
  JobPage,
  JobReferralPage,
  LeaderboardPage,
  LiveSupportPage,
  MessagesPage,
  MyJobsPage,
  NotificationSettingsPage,
  NotificationsPage,
  PartnersPage,
  PartnerCardPreviewPage,
  PerformanceScorePage,
  PhotoGalleryPage,
  ProfilePage,
  ReferralEarningsPage,
  ReferralPage,
  RegionsPage,
  ReviewsPage,
  SatisfactionPage,
  ServicesPage,
  StrategyPage,
  SubscriptionPage,
  SupportPage,
  TeamPage,
  UiKitPage,
  VueJobReferralPage,
  WalletPage,
  WorkingHoursPage,
} from "./index.js";
import { BlankRoutePage } from "./BlankRoutePage.js";

export const pageRoutes = {
  "/home": HomePage,
  "/jobs": JobPage,
  "/job-referral": JobReferralPage,
  "/my-jobs": MyJobsPage,
  "/calendar": CalendarPage,
  "/wallet": WalletPage,
  "/profile": ProfilePage,
  "/partner-card-preview": PartnerCardPreviewPage,
  "/notifications": NotificationsPage,
  "/support": SupportPage,
  "/support/new": CreateTicketPage,
  "/support/live": LiveSupportPage,
  "/support/customer-service": CustomerServicePage,
  "/messages": MessagesPage,
  "/reviews": ReviewsPage,
  "/satisfaction": SatisfactionPage,
  "/messages": MessagesPage,
  "/leaderboard": LeaderboardPage,
  "/partners": PartnersPage,
  "/customers": CustomersPage,
  "/referral": ReferralPage,
  "/referral-earnings": ReferralEarningsPage,
  "/subscription": SubscriptionPage,
  "/bonus": BonusPage,
  "/customer-management": () => BlankRoutePage({ title: "Müşteri Yönetimi", route: "/customer-management", showBack: true }),
  "/account-transactions": () => BlankRoutePage({ title: "Hesap Hareketleri", route: "/account-transactions", showBack: true }),
  "/digital-service-form": () => BlankRoutePage({ title: "Dijital Servis Formu", route: "/digital-service-form", showBack: true }),
  "/create-offer": () => BlankRoutePage({ title: "Teklif Oluştur", route: "/create-offer", showBack: true }),
  "/appointment-link": AppointmentLinkPage,
  "/performance-score": PerformanceScorePage,
  "/account-settings": AccountSettingsPage,
  "/notification-settings": NotificationSettingsPage,
  "/contact-settings": ContactSettingsPage,
  "/invoices": InvoicesPage,
  "/income-expense": IncomeExpensePage,
  "/photo-gallery": PhotoGalleryPage,
  "/about": AboutPage,
  "/services": ServicesPage,
  "/regions": RegionsPage,
  "/working-hours": WorkingHoursPage,
  "/team": TeamPage,
  "/capacity": CapacityPage,
  "/strategy": StrategyPage,
  "/ui-kit": UiKitPage,
  "/vue-job-referral": VueJobReferralPage,
};
