import {
  AboutPage,
  AccountSettingsPage,
  AppointmentLinkPage,
  BonusPage,
  CalendarPage,
  CapacityPage,
  ContactSettingsPage,
  CreateTicketPage,
  CustomersPage,
  HomePage,
  IncomeExpensePage,
  InvoicesPage,
  JobPage,
  JobReferralPage,
  LeaderboardPage,
  MessagesPage,
  MyJobsPage,
  NotificationSettingsPage,
  NotificationsPage,
  PackageBuilderPage,
  PackageCheckoutPage,
  PackagesPage,
  PartnersPage,
  PerformanceScorePage,
  PhotoGalleryPage,
  ProfilePage,
  ReferralEarningsPage,
  ReferralPage,
  RegionsPage,
  ReviewsPage,
  SatisfactionPage,
  ServicesPage,
  StrategyPage,
  SubscriptionPage,
  SupportPage,
  TeamPage,
  UiKitPage,
  VueJobReferralPage,
  WalletPage,
  WorkingHoursPage,
} from "./index.js";

export const pageRoutes = {
  "/home": HomePage,
  "/jobs": JobPage,
  "/job-referral": JobReferralPage,
  "/my-jobs": MyJobsPage,
  "/calendar": CalendarPage,
  "/wallet": WalletPage,
  "/profile": ProfilePage,
  "/notifications": NotificationsPage,
  "/support": SupportPage,
  "/support/new": CreateTicketPage,
  "/messages": MessagesPage,
  "/reviews": ReviewsPage,
  "/satisfaction": SatisfactionPage,
  "/leaderboard": LeaderboardPage,
  "/partners": PartnersPage,
  "/customers": CustomersPage,
  "/referral": ReferralPage,
  "/referral-earnings": ReferralEarningsPage,
  "/packages": PackagesPage,
  "/package-builder": PackageBuilderPage,
  "/package-checkout": PackageCheckoutPage,
  "/subscription": SubscriptionPage,
  "/bonus": BonusPage,
  "/appointment-link": AppointmentLinkPage,
  "/performance-score": PerformanceScorePage,
  "/account-settings": AccountSettingsPage,
  "/notification-settings": NotificationSettingsPage,
  "/contact-settings": ContactSettingsPage,
  "/invoices": InvoicesPage,
  "/income-expense": IncomeExpensePage,
  "/photo-gallery": PhotoGalleryPage,
  "/about": AboutPage,
  "/services": ServicesPage,
  "/regions": RegionsPage,
  "/working-hours": WorkingHoursPage,
  "/team": TeamPage,
  "/capacity": CapacityPage,
  "/strategy": StrategyPage,
  "/ui-kit": UiKitPage,
  "/vue-job-referral": VueJobReferralPage,
};
