export const ROUTE_TO_SCREEN = {
  "/home": "home",
  "/jobs": "work",
  "/my-jobs": "jobs",
  "/calendar": "calendar",
  "/wallet": "wallet",
  "/profile": "profile",
  "/notifications": "notifications",
  "/support": "support",
  "/messages": "messages",
  "/reviews": "reviews",
  "/leaderboard": "levels",
  "/partners": "referralList",
  "/customers": "customers",
  "/referral": "referral",
  "/referral-earnings": "referralEarnings",
  "/packages": "growthPackages",
  "/package-builder": "growthPackageBuilder",
  "/package-checkout": "growthPackageCheckout",
  "/subscription": "subscription",
  "/account-settings": "accountSettings",
  "/notification-settings": "notificationSettings",
  "/contact-settings": "contactSettings",
  "/invoices": "invoices",
  "/income-expense": "incomeExpense",
  "/photo-gallery": "photoGallery",
  "/about": "about",
  "/services": "services",
  "/regions": "regions",
  "/working-hours": "workPlan",
  "/team": "team",
  "/capacity": "capacity",
  "/strategy": "strategy",
  "/bonus": "bonus",
  "/appointment-link": "appointmentLink",
  "/performance-score": "performanceScore",
};

export const ROUTE_TITLES = {
  "/home": "Ana Sayfa",
  "/jobs": "İş Al",
  "/my-jobs": "İşlerim",
  "/calendar": "Takvim",
  "/wallet": "Cüzdan",
  "/profile": "Profilim",
  "/notifications": "Bildirimler",
  "/support": "Yardım ve Destek",
  "/messages": "Mesaj Kutusu",
  "/reviews": "Müşteri Yorumları",
  "/leaderboard": "Liderlik Tablosu",
  "/partners": "Partnerlerim",
  "/customers": "Müşteri Defteri",
  "/referral": "Partner Kazan",
  "/referral-earnings": "Kazançlarım",
  "/packages": "Büyüme Paketleri",
  "/package-builder": "Paket Seçimi",
  "/package-checkout": "Ödeme",
  "/subscription": "Aboneliğim",
  "/account-settings": "Hesap Ayarları",
  "/notification-settings": "Bildirim Ayarları",
  "/contact-settings": "İletişim Bilgileri",
  "/invoices": "Faturalarım",
  "/income-expense": "Gelir Gider Takibi",
  "/photo-gallery": "Fotoğraflarım",
  "/about": "Hakkımda",
  "/services": "Hizmetlerim",
  "/regions": "Bölgelerim",
  "/working-hours": "Saatlerim",
  "/team": "Ekibim",
  "/capacity": "Kapasitem",
  "/strategy": "Stratejim",
  "/bonus": "Bonus Cüzdanı",
  "/appointment-link": "Randevu Linki",
  "/performance-score": "Performans Skoru",
};

export const BOTTOM_TABS = [
  { id: "home", route: "/home", label: "Ana Sayfa", icon: "home" },
  { id: "jobs", route: "/my-jobs", label: "İşlerim", icon: "clipboard" },
  { id: "work", route: "/jobs", label: "İş Al", icon: "plus", featured: true, badge: 3 },
  { id: "calendar", route: "/calendar", label: "Takvim", icon: "calendar" },
  { id: "wallet", route: "/wallet", label: "Cüzdan", icon: "wallet" },
];

export const DRAWER_SECTIONS = [
  {
    title: "Büyüme",
    items: [
      { label: "Partnerlerim", icon: "share", route: "/partners", screen: "referralList", color: "#067647" },
      { label: "Liderlik Tablosu", icon: "trophy", route: "/leaderboard", screen: "levels", color: "#b54708" },
      { label: "Müşteri Yorumları", icon: "message", route: "/reviews", screen: "reviews", color: "#175cd3" },
      { label: "Kazanç Ortaklığı", icon: "briefcase", route: "/referral", screen: "referral", color: "#0e7490" },
      { label: "Büyüme Paketleri", icon: "package", route: "/packages", screen: "growthPackages", color: "#16a34a" },
      { label: "Aboneliğim", icon: "crown", route: "/subscription", screen: "subscription", color: "#d99a0b" },
    ],
  },
  {
    title: "Finans",
    items: [
      { label: "Hesap Hareketleri", icon: "credit-card", route: "/wallet", screen: "wallet", color: "#344054" },
      { label: "Faturalarım", icon: "receipt", route: "/invoices", screen: "invoices", color: "#b54708" },
    ],
  },
  {
    title: "İş Yönetimi",
    items: [
      { label: "Müşteri Kayıt Yönetimi", icon: "users", route: "/customers", screen: "customers", color: "#344054" },
      { label: "Gelir Gider Takibi", icon: "bar-chart", route: "/income-expense", screen: "incomeExpense", color: "#067647" },
      { label: "Servis Fişi", icon: "file-text", route: "/my-jobs", screen: "jobs", color: "#475467" },
      { label: "Garanti Formu", icon: "shield", route: "/my-jobs", screen: "jobs", color: "#175cd3" },
      { label: "Görüşme Kayıtlarım", icon: "phone", route: "/messages", screen: "messages", color: "#067647" },
      { label: "Ajanda", icon: "calendar", route: "/calendar", screen: "calendar", color: "#175cd3" },
      { label: "Teklif Oluştur", icon: "edit", route: "/jobs", screen: "work", color: "#6941c6" },
    ],
  },
];

export const PROFILE_MENU_ITEMS = [
  { label: "Hakkımda", shortLabel: "Hakkımda", route: "/about", screen: "about", icon: "user" },
  { label: "Fotoğraflarım", shortLabel: "Fotoğraf", route: "/photo-gallery", screen: "photoGallery", icon: "eye" },
  { label: "Hizmetlerim", shortLabel: "Hizmet", route: "/services", screen: "services", icon: "briefcase" },
  { label: "Bölgelerim", shortLabel: "Bölge", route: "/regions", screen: "regions", icon: "map-pin" },
  { label: "Saatlerim", shortLabel: "Saat", route: "/working-hours", screen: "workPlan", icon: "clock" },
  { label: "Ekibim", shortLabel: "Ekip", route: "/team", screen: "team", icon: "users" },
  { label: "Kapasitem", shortLabel: "Kapasite", route: "/capacity", screen: "capacity", icon: "bar-chart" },
  { label: "Stratejim", shortLabel: "Strateji", route: "/strategy", screen: "strategy", icon: "trend-up" },
];
