export const ROUTE_TO_SCREEN = {
  "/home": "home",
  "/jobs": "work",
  "/my-jobs": "jobs",
  "/calendar": "calendar",
  "/wallet": "wallet",
  "/profile": "profile",
  "/notifications": "notifications",
  "/support": "support",
  "/support/new": "supportNew",
  "/support/live": "supportLive",
  "/support/customer-service": "supportCustomerService",
  "/satisfaction": "satisfaction",
  "/messages": "messages",
  "/reviews": "reviews",
  "/leaderboard": "levels",
  "/partners": "referralList",
  "/customers": "customers",
  "/referral": "referral",
  "/referral/tasks": "referralTasks",
  "/referral/partners": "referralPartners",
  "/job-referral": "jobReferral",
  "/referral-earnings": "referralEarnings",
  "/subscription": "subscription",
  "/account-settings": "accountSettings",
  "/notification-settings": "notificationSettings",
  "/contact-settings": "contactSettings",
  "/invoices": "invoices",
  "/income-expense": "incomeExpense",
  "/photo-gallery": "photoGallery",
  "/about": "about",
  "/services": "services",
  "/regions": "regions",
  "/working-hours": "workPlan",
  "/team": "team",
  "/capacity": "capacity",
  "/strategy": "strategy",
  "/ui-kit": "uiKit",
  "/bonus": "bonus",
  "/appointment-link": "appointmentLink",
  "/performance-score": "performanceScore",
  "/partner-card-preview": "partnerCardPreview",
};

export const ROUTE_TITLES = {
  "/home": "Ana Sayfa",
  "/jobs": "Ä°ÅŸ Al",
  "/my-jobs": "Ä°ÅŸler",
  "/calendar": "Randevu",
  "/wallet": "CÃ¼zdan",
  "/profile": "Profilim",
  "/notifications": "Bildirimler",
  "/support": "YardÄ±m ve Destek",
  "/support/new": "Talep OluÅŸtur",
  "/support/live": "CanlÄ± Destek",
  "/support/customer-service": "MÃ¼ÅŸteri Hizmetleri",
  "/satisfaction": "Memnuniyet",
  "/messages": "Mesaj Kutusu",
  "/reviews": "MÃ¼ÅŸteri YorumlarÄ±",
  "/leaderboard": "Liderlik Tablosu",
  "/partners": "Davet EttiÄŸin Partnerler",
  "/customers": "MÃ¼ÅŸteri Defteri",
  "/referral": "Partner Davet ProgramÄ±",
  "/referral/tasks": "Referral GÃ¶revleri",
  "/referral/partners": "Davet EttiÄŸin Partnerler",
  "/job-referral": "Ä°ÅŸ YÃ¶nlendirme ProgramÄ±",
  "/referral-earnings": "KazanÃ§larÄ±m",
  "/subscription": "AboneliÄŸim",
  "/account-settings": "Hesap AyarlarÄ±",
  "/notification-settings": "Bildirim AyarlarÄ±",
  "/contact-settings": "Ä°letiÅŸim Bilgileri",
  "/invoices": "FaturalarÄ±m",
  "/income-expense": "Gelir Gider Takibi",
  "/photo-gallery": "FotoÄŸraflarÄ±m",
  "/about": "HakkÄ±mda",
  "/services": "Hizmetlerim",
  "/regions": "BÃ¶lgelerim",
  "/working-hours": "Saatlerim",
  "/team": "Ekibim",
  "/capacity": "Kapasitem",
  "/strategy": "Stratejim",
  "/ui-kit": "Vue UI Kit",
  "/bonus": "Bonus CÃ¼zdanÄ±",
  "/appointment-link": "Randevu Linki",
  "/performance-score": "Performans Skoru",
  "/partner-card-preview": "Partner KartÄ± Ã–nizleme",
};

export const BOTTOM_TABS = [
  { id: "home", route: "/home", label: "Ana Sayfa", icon: "home" },
  { id: "jobs", route: "/my-jobs", label: "Ä°ÅŸler", icon: "clipboard" },
  { id: "work", route: "/jobs", label: "Ä°ÅŸ Al", icon: "plus", featured: true, badge: 3 },
  { id: "calendar", route: "/calendar", label: "Randevu", icon: "calendar" },
  { id: "wallet", route: "/wallet", label: "CÃ¼zdan", icon: "wallet" },
];

export const RETIRED_ROUTE_REDIRECTS = {
  "/packages": "/subscription",
  "/package-builder": "/subscription",
  "/package-checkout": "/subscription",
  "/partner/packages": "/subscription",
};

export const DRAWER_SECTIONS = [
  {
    title: "BÃ¼yÃ¼me",
    items: [
      { label: "Liderlik Tablosu", icon: "trophy", route: "/leaderboard", screen: "levels", tone: "gold" },
      { label: "MÃ¼ÅŸteri YorumlarÄ±", icon: "message", route: "/reviews", screen: "reviews", tone: "blue" },
      { label: "AboneliÄŸim", icon: "crown", route: "/subscription", screen: "subscription", tone: "gold" },
    ],
  },
  {
    title: "KazanÃ§ OrtaklÄ±ÄŸÄ±",
    items: [
      {
        label: "Partner Davet ProgramÄ±",
        icon: "users",
        route: "/referral",
        screen: "referral",
        tone: "green",
      },
      {
        label: "Ä°ÅŸ YÃ¶nlendirme ProgramÄ±",
        icon: "briefcase",
        route: "/job-referral",
        screen: "jobReferral",
        tone: "blue",
      },
    ],
  },
  {
    title: "Finans",
    items: [
      { label: "Bonus GeÃ§miÅŸi", icon: "gift", route: "/bonus", screen: "bonus", tone: "blue" },
      { label: "Gelir / Gider", icon: "bar-chart", route: "/income-expense", screen: "incomeExpense", tone: "green" },
      { label: "FaturalarÄ±m", icon: "receipt", route: "/invoices", screen: "invoices", tone: "gold" },
    ],
  },
  {
    title: "Destek",
    items: [
      { label: "Talep OluÅŸtur", icon: "file-text", route: "/support/new", screen: "supportNew", tone: "green" },
      { label: "CanlÄ± Destek", icon: "message", route: "/support/live", screen: "supportLive", tone: "green" },
      { label: "MÃ¼ÅŸteri Hizmetleri", icon: "phone", route: "/support/customer-service", screen: "supportCustomerService", tone: "blue" },
    ],
  },
];

export const PROFILE_MENU_ITEMS = [
  { label: "HakkÄ±mda", shortLabel: "HakkÄ±mda", route: "/about", screen: "about", icon: "user" },
  { label: "FotoÄŸraflarÄ±m", shortLabel: "FotoÄŸraf", route: "/photo-gallery", screen: "photoGallery", icon: "eye" },
  { label: "Hizmetlerim", shortLabel: "Hizmet", route: "/services", screen: "services", icon: "briefcase" },
  { label: "BÃ¶lgelerim", shortLabel: "BÃ¶lge", route: "/regions", screen: "regions", icon: "map-pin" },
  { label: "Saatlerim", shortLabel: "Saat", route: "/working-hours", screen: "workPlan", icon: "clock" },
  { label: "Ekibim", shortLabel: "Ekip", route: "/team", screen: "team", icon: "users" },
  { label: "Kapasitem", shortLabel: "Kapasite", route: "/capacity", screen: "capacity", icon: "bar-chart" },
  { label: "Stratejim", shortLabel: "Strateji", route: "/strategy", screen: "strategy", icon: "trend-up" },
];
