export const ROUTE_TO_SCREEN = {
  "/home": "home",
  "/jobs": "work",
  "/my-jobs": "jobs",
  "/calendar": "calendar",
  "/wallet": "wallet",
  "/profile": "profile",
  "/notifications": "notifications",
  "/support": "support",
  "/support/new": "supportNew",
  "/support/live": "supportLive",
  "/satisfaction": "satisfaction",
  "/messages": "messages",
  "/reviews": "reviews",
  "/leaderboard": "levels",
  "/partners": "referralList",
  "/customers": "customers",
  "/referral": "referral",
  "/job-referral": "jobReferral",
  "/referral-earnings": "referralEarnings",
  "/packages": "growthPackages",
  "/package-builder": "growthPackageBuilder",
  "/package-checkout": "growthPackageCheckout",
  "/subscription": "subscription",
  "/account-settings": "accountSettings",
  "/notification-settings": "notificationSettings",
  "/contact-settings": "contactSettings",
  "/invoices": "invoices",
  "/income-expense": "incomeExpense",
  "/photo-gallery": "photoGallery",
  "/about": "about",
  "/services": "services",
  "/regions": "regions",
  "/working-hours": "workPlan",
  "/team": "team",
  "/capacity": "capacity",
  "/strategy": "strategy",
  "/ui-kit": "uiKit",
  "/vue-job-referral": "vueJobReferral",
  "/bonus": "bonus",
  "/appointment-link": "appointmentLink",
  "/performance-score": "performanceScore",
  "/partner-card-preview": "partnerCardPreview",
};

export const ROUTE_TITLES = {
  "/home": "Ana Sayfa",
  "/jobs": "İş Al",
  "/my-jobs": "İşlerim",
  "/calendar": "Takvim",
  "/wallet": "Cüzdan",
  "/profile": "Profilim",
  "/notifications": "Bildirimler",
  "/support": "Yardım ve Destek",
  "/support/new": "Talep Oluştur",
  "/support/live": "Canlı Destek",
  "/satisfaction": "Memnuniyet",
  "/messages": "Mesaj Kutusu",
  "/reviews": "Müşteri Yorumları",
  "/leaderboard": "Liderlik Tablosu",
  "/partners": "Davet Ettiğin Partnerler",
  "/customers": "Müşteri Defteri",
  "/referral": "Partner Davet Programı",
  "/job-referral": "İş Yönlendirme Programı",
  "/referral-earnings": "Kazançlarım",
  "/packages": "Büyüme Paketleri",
  "/package-builder": "Paket Seçimi",
  "/package-checkout": "Ödeme",
  "/subscription": "Aboneliğim",
  "/account-settings": "Hesap Ayarları",
  "/notification-settings": "Bildirim Ayarları",
  "/contact-settings": "İletişim Bilgileri",
  "/invoices": "Faturalarım",
  "/income-expense": "Gelir Gider Takibi",
  "/photo-gallery": "Fotoğraflarım",
  "/about": "Hakkımda",
  "/services": "Hizmetlerim",
  "/regions": "Bölgelerim",
  "/working-hours": "Saatlerim",
  "/team": "Ekibim",
  "/capacity": "Kapasitem",
  "/strategy": "Stratejim",
  "/ui-kit": "Vue UI Kit",
  "/vue-job-referral": "İş Yönlendirme Vue Pilot",
  "/bonus": "Bonus Cüzdanı",
  "/appointment-link": "Randevu Linki",
  "/performance-score": "Performans Skoru",
  "/partner-card-preview": "Partner Kartı Önizleme",
};

export const BOTTOM_TABS = [
  { id: "home", route: "/home", label: "Ana Sayfa", icon: "home" },
  { id: "jobs", route: "/my-jobs", label: "İşlerim", icon: "clipboard" },
  { id: "work", route: "/jobs", label: "İş Al", icon: "plus", featured: true, badge: 3 },
  { id: "calendar", route: "/calendar", label: "Takvim", icon: "calendar" },
  { id: "wallet", route: "/wallet", label: "Cüzdan", icon: "wallet" },
];

export const DRAWER_SECTIONS = [
  {
    title: "Büyüme",
    items: [
      { label: "Liderlik Tablosu", icon: "trophy", route: "/leaderboard", screen: "levels", color: "#b54708" },
      { label: "Müşteri Yorumları", icon: "message", route: "/reviews", screen: "reviews", color: "#175cd3" },
      { label: "Paketler", icon: "package", route: "/packages", screen: "growthPackages", color: "#16a34a" },
      { label: "Aboneliğim", icon: "crown", route: "/subscription", screen: "subscription", color: "#d99a0b" },
    ],
  },
  {
    title: "Kazanç Ortaklığı",
    items: [
      {
        label: "Partner Davet Programı",
        icon: "users",
        route: "/referral",
        screen: "referral",
        color: "#067647",
      },
      {
        label: "İş Yönlendirme Programı",
        icon: "briefcase",
        route: "/job-referral",
        screen: "jobReferral",
        color: "#175cd3",
      },
    ],
  },
  {
    title: "Finans",
    items: [
      { label: "Hesap Hareketleri", icon: "credit-card", route: "/wallet", screen: "wallet", color: "#344054" },
      { label: "Kredi Geçmişi", icon: "credit-card", route: "/wallet", screen: "wallet", color: "#475467" },
      { label: "Bonus Geçmişi", icon: "gift", route: "/bonus", screen: "bonus", color: "#175cd3" },
      { label: "Gelir / Gider", icon: "bar-chart", route: "/income-expense", screen: "incomeExpense", color: "#067647" },
      { label: "Faturalarım", icon: "receipt", route: "/invoices", screen: "invoices", color: "#b54708" },
    ],
  },
  {
    title: "Destek",
    items: [
      { label: "Talep Oluştur", icon: "file-text", route: "/support/new", screen: "supportNew", color: "#067647" },
      { label: "Canlı Destek", icon: "message", route: "/support/live", screen: "supportLive", color: "#067647" },
    ],
  },
];

export const PROFILE_MENU_ITEMS = [
  { label: "Hakkımda", shortLabel: "Hakkımda", route: "/about", screen: "about", icon: "user" },
  { label: "Fotoğraflarım", shortLabel: "Fotoğraf", route: "/photo-gallery", screen: "photoGallery", icon: "eye" },
  { label: "Hizmetlerim", shortLabel: "Hizmet", route: "/services", screen: "services", icon: "briefcase" },
  { label: "Bölgelerim", shortLabel: "Bölge", route: "/regions", screen: "regions", icon: "map-pin" },
  { label: "Saatlerim", shortLabel: "Saat", route: "/working-hours", screen: "workPlan", icon: "clock" },
  { label: "Ekibim", shortLabel: "Ekip", route: "/team", screen: "team", icon: "users" },
  { label: "Kapasitem", shortLabel: "Kapasite", route: "/capacity", screen: "capacity", icon: "bar-chart" },
  { label: "Stratejim", shortLabel: "Strateji", route: "/strategy", screen: "strategy", icon: "trend-up" },
];
