import {
  AlertTriangle,
  BarChart3,
  Bell,
  Briefcase,
  Calendar,
  Check,
  ChevronLeft,
  ChevronRight,
  ClipboardList,
  Clock,
  CreditCard,
  Crown,
  Eye,
  Gift,
  Home,
  Image,
  MapPin,
  MessageCircle,
  Plus,
  Search,
  Send,
  Settings,
  Shield,
  Star,
  Target,
  Trophy,
  User,
  Users,
  Wallet,
  X,
  Zap,
} from "lucide-vue-next";

export const iconMap = {
  alert: AlertTriangle,
  "bar-chart": BarChart3,
  bell: Bell,
  briefcase: Briefcase,
  calendar: Calendar,
  check: Check,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  clipboard: ClipboardList,
  clock: Clock,
  "credit-card": CreditCard,
  crown: Crown,
  eye: Eye,
  gift: Gift,
  home: Home,
  image: Image,
  "map-pin": MapPin,
  message: MessageCircle,
  plus: Plus,
  search: Search,
  send: Send,
  settings: Settings,
  shield: Shield,
  star: Star,
  target: Target,
  trophy: Trophy,
  user: User,
  users: Users,
  wallet: Wallet,
  x: X,
  zap: Zap,
};

export function resolveIcon(name) {
  return iconMap[name] || iconMap.settings;
}
