import {
  AlertTriangle,
  BarChart3,
  Bell,
  Briefcase,
  Calendar,
  CalendarCheck,
  Check,
  ChevronLeft,
  ChevronRight,
  ClipboardList,
  Clock,
  CreditCard,
  Crown,
  Eye,
  FileText,
  Gift,
  Globe2,
  Headphones,
  HelpCircle,
  Home,
  Image,
  Info,
  Instagram,
  Link2,
  Lock,
  Menu,
  MapPin,
  MessageCircle,
  Minus,
  Pause,
  Pencil,
  Phone,
  Plus,
  QrCode,
  ReceiptText,
  RefreshCw,
  Search,
  Send,
  Settings,
  Share2,
  Shield,
  Sparkles,
  Star,
  Target,
  TrendingUp,
  Trophy,
  User,
  Users,
  Video,
  Wallet,
  X,
  Zap,
} from "lucide-vue-next";

export const iconMap = {
  alert: AlertTriangle,
  "bar-chart": BarChart3,
  bell: Bell,
  briefcase: Briefcase,
  calendar: Calendar,
  "calendar-check": CalendarCheck,
  check: Check,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  clipboard: ClipboardList,
  clock: Clock,
  "credit-card": CreditCard,
  crown: Crown,
  eye: Eye,
  "file-text": FileText,
  gift: Gift,
  globe: Globe2,
  headphones: Headphones,
  "help-circle": HelpCircle,
  home: Home,
  image: Image,
  info: Info,
  instagram: Instagram,
  link: Link2,
  lock: Lock,
  menu: Menu,
  "map-pin": MapPin,
  message: MessageCircle,
  minus: Minus,
  pause: Pause,
  edit: Pencil,
  phone: Phone,
  plus: Plus,
  qr: QrCode,
  receipt: ReceiptText,
  refresh: RefreshCw,
  search: Search,
  send: Send,
  settings: Settings,
  share: Share2,
  shield: Shield,
  sparkles: Sparkles,
  star: Star,
  target: Target,
  "trend-up": TrendingUp,
  trophy: Trophy,
  user: User,
  users: Users,
  video: Video,
  wallet: Wallet,
  x: X,
  zap: Zap,
};

export function resolveIcon(name) {
  return iconMap[name] || iconMap.settings;
}
